### ISSUE TITLE
Pinia 2.1.0 + Vue 2.7.14: Error "VueCompositionAPI is not defined" in hasInjectionContext()

### ISSUE THREAD

**Issue by tkallage** [posva/pinia#2208]
### Reproduction

https://jsfiddle.net/egay83mp/4/

### Steps to reproduce the bug

Use Pinia 2.1 with Vue 2.7.14

### Expected behavior

no exception is thrown

### Actual behavior

An exception is thrown when using a defined store:
![grafik](https://github.com/vueuse/vue-demi/assets/8417407/c7a0f472-6e9e-471c-bca9-a241d615651d)
![grafik](https://github.com/vueuse/vue-demi/assets/8417407/a8cec172-be51-48e1-afb9-51eab5c49337)
![grafik](https://github.com/vueuse/vue-demi/assets/8417407/674c9389-5a51-4898-8fed-4110a2f52e2d)

### Additional information

Opened issue in vue-demi:
https://github.com/vueuse/vue-demi/issues/224

JSFiddle with Pinia 2.0 (working):
https://jsfiddle.net/mk56hoqe/2/
JSFiddle with Pinia 2.1 (broken):
https://jsfiddle.net/egay83mp/4/

**Comment by softy2k** [comment]
Same issue.
Reverting to **2.0.36**

**Comment by LiuJiaWeb** [comment]
Update Pinia to v2.1.0，Vue version is v2.7.14
I also ran into this bug

**Comment by posva** [comment]
I overlooked iife when adding the feature to vue-demi. I opened a PR to fix it https://github.com/vueuse/vue-demi/pull/225

**Comment by posva** [comment]
A fix was released in vue-demi 💯

**Comment by K4T** [comment]
Unfortunately after spending hours on it I also had to rollback to 2.0.36 to fix the same problem in my project.

For Pinia 2.1.1 with Vue 2.7.14 bug still appear.

**Comment by tkallage** [comment]
I can confirm, that the error still exists in pinia 2.1.1 / vue-demi 0.14.3.

I opened a new issue in the vue-demi repository with updated example code:

https://github.com/vueuse/vue-demi/issues/228

**Comment by posva** [comment]
After https://github.com/vueuse/vue-demi/pull/229, all possible versions should be properly covered 😅
