### ISSUE TITLE
Can't reset store state / patch with pinia@2.0.0-rc.0

### ISSUE THREAD

**Issue by slauzinho** [posva/pinia#593]
First of all thank you for your amazing work, I'm really excited to try all the new features coming into Pinia.

### Reproduction

I tried the new version of pinia and it seems the `store.$reset()` is no longer working or the api changed.

I created a repro with the issue: https://github.com/slauzinho/pinia-example-reset

### Steps to reproduce the behavior

1. Call `store.$reset`
2. State remains the same

### Expected behavior

State should be the same as the initial

### Actual behavior

State doesn't change

**Comment by posva** [comment]
The `$reset()` function is not correctly keeping existing refs, ending up in `store.$state.data != store.data`.

**Comment by slauzinho** [comment]
@posva Is the issue with `$patch` also related?

On that demo repo if you try:

```typescript
counterStore.$patch({
  counter: 10
})
```

It doesn't change the value

**Comment by posva** [comment]
Using `$reset()` broke the reactivity, but it seems fixed in rc.1

**Comment by Blackfaded** [comment]
Having the same issue right now in my unit tests with rc 6.
Calling `store.$reset()` in the beforeEach blocks do not reset the state.

Example:

top level jest function:
```ts
  let configuratorStore: ReturnType<typeof useConfiguratorStore>;
  let mediaStore: ReturnType<typeof useMediaStore>;
  beforeEach(() => {
    setActivePinia(createPinia());
    configuratorStore = useConfiguratorStore();
    mediaStore = useMediaStore();
  });
  afterEach(() => {
    configuratorStore.$reset();
    mediaStore.$reset();
  });

```


actual unit test:
```ts
describe('name does exist', () => {
          beforeEach(() => {
            configuratorStore.$patch({name: "test"});
          });
          it('should return the name', async () => {
            expect(configuratorStore.selectedName).toEqual('test');
          });
        });

        describe('and the template does not exist', () => {
          it('should return an empty string', async () => {
            const selectedName = configuratorStore.selectedName;
            expect(selectedName).toEqual('');
          });
        });
```

The second test fails and the name is still `'test'`

**Comment by Blackfaded** [comment]
Solved it by replacing the state definition from

```ts
  state: () => initialConfiguratorState,
```

to

```ts
  state: () => {
    return { ...initialConfiguratorState };
  },
```

**Comment by slauzinho** [comment]
@Blackfaded this was addressed in a previous issue: https://github.com/posva/pinia/issues/484

**Comment by quantuminformation** [comment]
@Blackfaded I have this:

```js

beforeEach(() => {
  setActivePinia(createPinia())
  store = useVideoPlayerStore()
  store.$reset()
})
afterEach(() => {
  store.$reset()
})
```

and
```js
export const useVideoPlayerStore = defineStore("videoPlayerStore", {
  state: () => ({ ...initialVideoPlayerState }),
```
And still get state preserved across tests
