### ISSUE TITLE
[Kit] You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by darthf1** [posva/pinia#737]
Hi!

I'm not sure where this belongs. Also reported in https://github.com/nuxt/nuxt.js/issues/9968.

This issue started with `@nuxt/pinia` `0.0.8`. When I go back to `0.0.7`, everything is ok.

### Versions

- nuxt: 2.15.8
- node: v16.11.1

### What is actually happening?

I'm a regular Nuxt 2 user, without any dependencies (direct) on `kit` or `bridge`. Today, I get this error:

```
#15 45.68 ERROR in ./node_modules/@nuxt/kit/dist/index.mjs 111:45
#15 45.68 Module parse failed: Unexpected token (111:45)
#15 45.68 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
#15 45.68 |   vue: {
#15 45.68 |     config: {
#15 45.68 >       silent: { $resolve: (val, get) => val ?? !get("dev") },
#15 45.68 |       performance: { $resolve: (val, get) => val ?? get("dev") }
#15 45.68 |     }
#15 45.68  @ ./node_modules/@pinia/nuxt/templates/plugin.js 4:12-32
#15 45.68  @ ./.nuxt/index.js
#15 45.68  @ ./.nuxt/client.js
#15 45.68  @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/composition-api/register.js ./.nuxt/client.js
```

`package-lock.json`
```json
"@pinia/nuxt": {
  "version": "0.0.8",
  "resolved": "https://registry.npmjs.org/@pinia/nuxt/-/nuxt-0.0.8.tgz",
  "integrity": "sha512-9urk4CKrZsEGDUOAqdGIh3NAHO6fOGORpBrIgejrxlq4zbRPue7Y+zlaqlou4JEHuXqdEyG9DyLp423cPB+GDw==",
  "requires": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@latest",
    "upath": "^2.0.1"
  }
},
"@nuxt/kit": {
  "version": "npm:@nuxt/kit-edge@3.0.0-27245975.d1214c9",
  "resolved": "https://registry.npmjs.org/@nuxt/kit-edge/-/kit-edge-3.0.0-27245975.d1214c9.tgz",
  "integrity": "sha512-vDBK6iu2+xdgsu40TbI6pew7sCqP9BqhEyQAiQednw6r3mwvXMYfGSJmBQqQaQxHpgaqmrlrVOhB3DH/34yHlA==",
  "requires": {
    "consola": "^2.15.3",
    "create-require": "^1.1.1",
    "defu": "^5.0.0",
    "dotenv": "^10.0.0",
    "globby": "^11.0.4",
    "hash-sum": "^2.0.0",
    "hookable": "^5.0.0",
    "jiti": "^1.12.9",
    "lodash.template": "^4.5.0",
    "mlly": "^0.3.0",
    "pathe": "^0.2.0",
    "pkg-types": "^0.2.1",
    "rc9": "^1.2.0",
    "scule": "^0.2.1",
    "semver": "^7.3.5",
    "std-env": "^2.3.1",
    "ufo": "^0.7.9",
    "unctx": "^1.0.2",
    "untyped": "^0.2.9"
  },
  "dependencies": {
    "semver": {
      "version": "7.3.5",
      "resolved": "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz",
      "integrity": "sha512-PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==",
      "requires": {
        "lru-cache": "^6.0.0"
      }
    }
  }
},
```

`nuxt.config.ts`
```js
build: {
    extend(config) {
      // remove this line after upgrading to nuxt 2.16
      config.module?.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
},

**Comment by posva** [comment]
The error doesn't seem to come from pinia. Do you have a boiled down reproduction, you should probably provide it on the nuxt issue so they can take a look.

**Comment by darthf1** [comment]
Thanks for looking into it!

I just upgraded from `0.0.7` to `0.0.9` and the issue is not there anymore. Strange, but lets close :D

```json
"@pinia/nuxt": {
  "version": "0.0.9",
  "resolved": "https://registry.npmjs.org/@pinia/nuxt/-/nuxt-0.0.9.tgz",
  "integrity": "sha512-cs/ut+sABrfXUmHo5Va7fSrPA2ySvKzs25JOfKW1+6eGheFNng45s4IwGmSp48dNczHuW3upYcOwe4mEuJBWhA==",
  "requires": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@latest",
    "vue-demi": "*"
  }
},
"@nuxt/kit": {
  "version": "npm:@nuxt/kit-edge@3.0.0-27245975.d1214c9",
  "resolved": "https://registry.npmjs.org/@nuxt/kit-edge/-/kit-edge-3.0.0-27245975.d1214c9.tgz",
  "integrity": "sha512-vDBK6iu2+xdgsu40TbI6pew7sCqP9BqhEyQAiQednw6r3mwvXMYfGSJmBQqQaQxHpgaqmrlrVOhB3DH/34yHlA==",
  "requires": {
    "consola": "^2.15.3",
    "create-require": "^1.1.1",
    "defu": "^5.0.0",
    "dotenv": "^10.0.0",
    "globby": "^11.0.4",
    "hash-sum": "^2.0.0",
    "hookable": "^5.0.0",
    "jiti": "^1.12.9",
    "lodash.template": "^4.5.0",
    "mlly": "^0.3.0",
    "pathe": "^0.2.0",
    "pkg-types": "^0.2.1",
    "rc9": "^1.2.0",
    "scule": "^0.2.1",
    "semver": "^7.3.5",
    "std-env": "^2.3.1",
    "ufo": "^0.7.9",
    "unctx": "^1.0.2",
    "untyped": "^0.2.9"
  },
  "dependencies": {
    "semver": {
      "version": "7.3.5",
      "resolved": "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz",
      "integrity": "sha512-PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==",
      "requires": {
        "lru-cache": "^6.0.0"
      }
    }
  }
},

**Comment by 7ochem** [comment]
For anyone ending up here for whom it doesn't solve to upgrade (or already on the latest version), see the solution here https://github.com/nuxt/nuxt/discussions/24304
