### ISSUE TITLE
@pinia/nuxt latest version gives error

### ISSUE THREAD

**Issue by Rigo-m** [posva/pinia#767]
### Reproduction

https://github.com/Rigo-m/pinia-issue-repro

### Steps to reproduce the behavior

1. `yarn`
2. `yarn dev`

### Expected behavior
Should work

### Actual behavior

Throws error because vue composition api is being imported twice

### Additional information
Latest node LTS

**Comment by posva** [comment]
This is likely related to the changes mentioned at https://github.com/vuejs/composition-api/releases/tag/v1.3.0

**Comment by Rigo-m** [comment]
Any ideas on how to make those workarounds works?

**Comment by Rigo-m** [comment]
Can we downgrade to 1.2.x? This is extremely blocking for any project

**Comment by Rigo-m** [comment]
@antfu any ideas?

**Comment by aparajita** [comment]
@Rigo-m Are you getting this warning?

`[warning] You are using CommonJS version of @nuxt/kit that is an ESM-only package. CJS support will be dropped in stable release.`

If I downgrade to `@pinia/nuxt@0.1.0` the error goes away.

**Comment by Rigo-m** [comment]
@aparajita IIRC correctly it doesn't. I have to spin up the repro again and I'm quite low on time today. But I think it only gave me the error about composition API.

**Comment by Rigo-m** [comment]
@aparajita the problem with `@pinia/nuxt@0.1.0` is that is gives an error while bundled in production (https://github.com/posva/pinia/discussions/747). So right now we are stuck with either a non-working version (`@pinia/nuxt@0.1.2`) or a production failing version. Honestly, I don't know what to do because I have a client meeting next friday and pinia has been a life saver for a lot of features that I can't show in production as of now...

**Comment by craigjamesdobson** [comment]
This seems to be an issue when using `nuxt3` beta too. Not sure if its the same issue but I thought I would make a note.

**Comment by Rigo-m** [comment]
@craigjamesdobson feel free to add a reproduction repository with nuxt3

**Comment by aparajita** [comment]
@craigjamesdobson We are using nuxt3 as well.

**Comment by posva** [comment]
This issue is with Nuxt 2 only. It's due to changes with composition-api, vue-demi, and the nuxt module.

Note I have [multiple examples](https://github.com/piniajs?q=example&type=&language=&sort=) and Nuxt Bridge and Nuxt 3 are working fine

**Comment by aparajita** [comment]
@posva I'm sorry to disagree, but as soon as I install > 0.1.0, I get this when starting nuxt3:

 WARN  [warning] You are using CommonJS version of @nuxt/kit that is an ESM-only package. CJS support will be dropped in stable release.

 ERROR  Cannot start nuxt:  loadNuxt is not a function

**Comment by posva** [comment]
This is not about disagreeing 😅.

I specifically created those repositories with automatic upgrades and tests to keep track of breakage and also to provide a working setup for others. When working with libraries that are updated every day like Nuxt beta, it's often necessary to regen the `yarn.lock` (or similar) or to completely reinstall some dependencies. Have you given that a try and compared the `nuxt.config.js` files?

**Comment by craigjamesdobson** [comment]
@posva The [demo](https://stackblitz.com/github/piniajs/example-nuxt-3) that is on readme was reproducing the same error. 
This demo doesn't seem to be working anymore but was yesterday.

**Comment by Rigo-m** [comment]
@posva  About nuxt 2, is the problem fixable quickly? I didn't quite understand who should fix this and if it's fixable in userland

**Comment by posva** [comment]
I don't know for Nuxt 2. I couldn't find the source of the problem but I shared it with the Nuxt team and they seem to know where this come from. Could even be fixed in the latest nuxt composition-api already.

**Comment by Rigo-m** [comment]
> I don't know for Nuxt 2. I couldn't find the source of the problem but I shared it with the Nuxt team and they seem to know where this come from. Could even be fixed in the latest nuxt composition-api already.

I see, thank you

**Comment by Rigo-m** [comment]
@posva FYI `@nuxtjs/composition-api` `v0.30.0` didn't fix the issue

**Comment by eMeRiKa13** [comment]
> @craigjamesdobson feel free to add a reproduction repository with nuxt3

You can try [this repo](https://github.com/productdevbook/nuxt3-app). The page returns an error 500. And there is an error message about Pinia

```
[SSR] Error transforming virtual: D:/.../nuxt3-test/.nuxt/plugins/server.mjs: Error: Failed to resolve import "D:

nuxt3-test/node_modules/@pinia/nuxt/dist/templates/plugin.mjs" from "virtual:D:\...\nuxt3-test\.nuxt\plugins\server.mjs". Does the file exist?
```

**Comment by craigjamesdobson** [comment]
> > @craigjamesdobson feel free to add a reproduction repository with nuxt3
> 
> You can try [this repo](https://github.com/productdevbook/nuxt3-app). The page returns an error 500. And there is an error message about Pinia
> 
> ```
> [SSR] Error transforming virtual: D:/.../nuxt3-test/.nuxt/plugins/server.mjs: Error: Failed to resolve import "D:
> 
> nuxt3-test/node_modules/@pinia/nuxt/dist/templates/plugin.mjs" from "virtual:D:\...\nuxt3-test\.nuxt\plugins\server.mjs". Does the file exist?
> ```

Yeah, this is the same error I get.

**Comment by Rigo-m** [comment]
@eMeRiKa13 @craigjamesdobson I guess it's a similar issue but I think it should stand in a different topic, because [this](https://github.com/nuxt-community/composition-api/commit/52cd2870e66c62ab95a62b32ca4d84d2715b0667) branch fixed the issue for nuxt2+composition api. So I guess nuxt3 is another thing altogether.

**Comment by tobiasdiez** [comment]
Maybe related, but upgrading pinia/nuxt from 0.1.0 to the latest 0.1.2 (with nuxt 2 without bridge) gives the following error:
```
[fatal] A dynamic import callback was not specified.
  at new NodeError (internal/errors.js:322:7)
  at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:34:9)
  at ModuleContainer.module.exports (node_modules/@pinia/nuxt/module.cjs:3:3)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```
(see https://github.com/JabRef/JabRefOnline/pull/616). I thought I will report this here but if you don't think that this is related to the problem with nuxt/composition-api, then I'll open a new issue.

**Comment by posva** [comment]
This should be good now! Let me know if you find issues by opening a new issue with a boiled down repro.

Refer to https://github.com/piniajs for examples with the proper configurations

**Comment by craigjamesdobson** [comment]
Nice one, thats all working now. Thanks for the fix!
